#!/bin/bash

if [ $# -lt 2 ]; then
    echo 'Usage: <IQ Panel Host> <IQ Panel Secure Token>'
    exit 1
fi

docker run --rm -it \
    -p 1880:1880 -p 1883:1883 \
    -v $PWD/shared:/iqmate -w /iqmate \
    -e IQPANEL_HOST=$1 -e IQPANEL_TOKEN=$2 \
    iqmate
